### ISSUE TITLE
Stops logging and fills buffer until full

### ISSUE THREAD

**Issue by ir-fuel** [rapid7/le_node#110]
This has happened a few times now in our Docker container. After a couple of days of running we get this:

`2016-05-14 12:41:40.587
{"v":0,"id":"8148c38e8ccd","image":"****","name":"****","line":"{ [LogentriesError: Buffer is full, unable to log: \"info Sending mail to Gerr ...\".]","host":"81fef9a3289d"}`

The only solution is to restart the container and then it works again for a while. The issue is that we lose a few days of logging data because they all get buffered up and never sent to logentries. We use this in several of our containers and there is only one exhibiting this behavior.

package.json contains:
`    "le_node": "^1.1.1" `

**Comment by timelessvirtues** [comment]
Exact same issue which keeps crashing our production systems.  Keep increasing the buffer size but it always happens eventually.

**Comment by Souler** [comment]
Confirmed on 1.3.0.

After 8 days running with no problem, the program suddenly stops sending logs.

**Comment by StephenHynes7** [comment]
@Souler did you encounter any network connectivity issues? 

https://github.com/logentries/le_node/pull/108
https://github.com/logentries/le_node/issues/101

**Comment by Souler** [comment]
@StephenHynes7 Sorry, I can't really tell.

Our app is running on a AWS ElasticBeanstalk instance and when I realised logentries logs weren't working the log files rotation system already deleted the ones I needed.

Don't know if it will be any help, but last log successfully sent (before restarting)  was on `20/May/2016:03:31:23 +0000`

**Comment by StephenHynes7** [comment]
@Souler np, what I would suggest just to be on the safe side is setting this value https://github.com/logentries/le_node/blob/master/src/node_modules/defaults.js#L6 to 100 or so.

**Comment by Souler** [comment]
Mmmm, that property is not editable as a consumer of `le_node` module, I'll try to add it to the constructor options and make a PR, maybe should also make `retryTimeout` configurable?

**Comment by StephenHynes7** [comment]
Hmm i thought it was, yes if you could do that then that would be great, i have a feeling that this value tends to be the root cause of these problems we burn through the timeouts too quickly and never retry after 15 attempts.

**Comment by StephenHynes7** [comment]
For those affected by this I have a PR for increasing the default buffer size which you can see here https://github.com/logentries/le_node/pull/108 

I am anxious to merge until I get more feedback so please have a look. 

As noted I think that if https://github.com/logentries/le_node/blob/master/src/node_modules/defaults.js#L6 is increased then that should prevent other issues we see but I am not 100% sure.

**Comment by ir-fuel** [comment]
Wouldn't editing the buffer size just postpone the problem? I am afraid of losing 3 days of log data instead of one.

**Comment by StephenHynes7** [comment]
Potentially but the other alternative is use a Ring Buffer and have some data loss when the buffer becomes full and we begin to over write data

**Comment by ir-fuel** [comment]
Just wondering if this not the wrong solution to the problem. Why does the system stop sending logs to logentries? I can't imagine it not being able to send data to their server for several days in a row?

**Comment by StephenHynes7** [comment]
@ir-fuel it seems to just stop once the buffer is full rather than trying to clear it. The other scenario is that it loses connectivity and tries to reconnect, if it does not reconnect after 15 attempts than it never reconnects.

**Comment by ir-fuel** [comment]
Is there some way I can log (oh the irony ...) what happens? I have production server that exhibits this every couple of days. Maybe this can help in finding out what causes it.

**Comment by StephenHynes7** [comment]
@ir-fuel sure

*Timeout* https://github.com/logentries/le_node/blob/master/src/node_modules/logger.js#L370

*Buffer Full* https://github.com/logentries/le_node/blob/master/src/node_modules/logger.js#L266

For the record, the way the code is currently implemented means we can not gracefully handle the buffer being full, if it is full the logging stops completely. In other LE libraries the pattern has usually involved some sort of Ring Buffer where if we for some reason fill the buffer we then start over writing the oldest items. This presumes though that you are able to work through sending logs. 

Maybe it's worth logging the average time it takes to send a log message?

Between https://github.com/logentries/le_node/blob/master/src/node_modules/logger.js#L156 and https://github.com/logentries/le_node/blob/master/src/node_modules/logger.js#L166

**Comment by bathos** [comment]
@StephenHynes7 That wouldn't tell you how long it takes to send the message, only how long it takes to serialize it and push it into the tls stream. The TLS stream may write immediately or it may be queued, we don't know at that point.

Re: the PR, though I mentioned my reservations, feel free to merge -- I'm really not sure what the best figure would be myself.

My assumptions about what behaviors would be desired in the event of a missing connection (or other condition leading to the buffer filling) were clearly incorrect. If you want to give me a sort of spec for what the best behavior should be I could look into implementing it today, I have a free day here owing to the US holiday.

**Comment by StephenHynes7** [comment]
@bathos thanks. The other libs generally follow the pattern of if the buffer is full then we begin to overwrite items from the beginning (see [here](https://github.com/logentries/le_java/blob/master/src/main/java/com/logentries/net/AsyncLogger.java#L421)).

The problem with implementing this pattern right now is that I would fear that we would easily get into a loop where we start overwriting logs too quickly because the buffer size is too small. I do think it needs to be increased, whether it needs to be 32k or something else I am not sure.

**Comment by bathos** [comment]
Sounds good, I'm cleaning stuff up presently and I believe this shouldn't be too tough (...well, we'll see). I've spotted a few things that could use some help along the way, like refactoring out some of the more curious design decisions (when I wrote this, I had only been using ES6 for a few months, and it shows), and I'm going to annotate some of it with comments so that it'll be easier for you or others to debug in the future. Let me know if there's a good way to chat, I wish Github had a mechanism for that beyond issue threads.

**Comment by ir-fuel** [comment]
Now a second server started exhibiting the same behavior.

This is not good :(

I don't think increasing the buffer or working with a circular one will remove the problem, it will just hide it (which is even worse).

Is this an official Logentries project btw? Or is this an open source lib developed by the community?

**Comment by bathos** [comment]
@ir-fuel I'm about halfway through a big cleanup that should address these issues. The most important change will be that serialization will be done prior to buffering, allowing us to specify a buffer size in terms of bytes instead of number of objects. The huge variability in what "1 object" can mean for memory usage has meant that any given limit is meaninglessly arbitrary, whereas with this change, we can crank the ceiling way up safely because it will always mean the same thing.

Dumping the oldest items when the buffer is full makes sense to me, but we could try to be clever and compress them into a single entry like 'LOGS LOST DUE TO FULL BUFFER' so that some notice of the occurrence hopefully comes through, but accruing indefinitely doesn't seem realistic to me. However the network backoff problem is a separate issue, and comparatively easy to solve. It seems likely that this is what really accounts for ending up with the full buffer in the first place.

The project is something I developed when I was an LE employee for a particular project, and it ended up supplanting the previous node lib as 'official'. It's open source, as was its predecessor, and I've continued to try to answer questions, review PRs, etc., but it is a Logentries repo.

**Comment by timelessvirtues** [comment]
A couple of things come to mind that would help address this issue:
1. Allow le_node consumer to specify retry count.
1. Implement some flavor of an adaptive back-off algorithm to delay successive reconnection attempts.
2. Offer an emergency buffer to disk backup option so when a connection does eventually get re-established the logs will eventually be sent to the server.

**Comment by gyakushev** [comment]
Have this error too.
What makes it worse is that the Error is thrown from log() call, interrupting the production user operation as well.

**Comment by Souler** [comment]
Happened again, logs didn't provide any help at all.
I'm available for helping with this topic.
I'm currently thinking about adding `debug` as a dep, add traces all over the place to `le_node` and start doing spike tests, any thoughts on this?

**Comment by ir-fuel** [comment]
Happened 2 times in a couple of hours here. I will have to start looking at another service as this is becoming too unreliable in a production environment.

On 27 jun. 2016, at 01:34, Juan Jos? Herrero Barbosa <notifications@github.com<mailto:notifications@github.com>> wrote:


Happened again, logs didn't provide any help at all.
I'm available for helping with this topic.
I'm currently thinking about adding debug as a dep, add traces all over the place to le_node and start doing spike tests, any thoughts on this?

-

**Comment by ksullivan** [comment]
I'm experiencing this bug and it's really annoying.

**Comment by timelessvirtues** [comment]
Since this has gone 6+ weeks without action I ended up installing the Linux agent, changing my application to log to disk then having the C++ agent watch those files before log rotating.  This is far from ideal because my bottleneck will quickly become disk I/O.

**Comment by andyburke** [comment]
Seeing this issue. I agree with @ir-fuel that the issue here is likely the reconnection limit, not the buffer size.

I don't think #111 addressed the issue. There should really be no maximum number of connection retries. Some kind of backoff scaling should handle that issue.

I will take a look to see if I can submit a PR, but I am pretty busy.

**Comment by markstos** [comment]
My workaround was to quit using this module. Instead, I log into STDOUT, redirect STDOUT to syslog and have rsyslog handle talking to Logentries.

The details of logging should not be the concern of the application. Logging to STDOUT is recommended by the [12 Factor App](http://12factor.net/logs) design. Newer process management tools are also made to play nicely with logs on STDOUT. Notably `systemd` is now standard on many Linux distributions and supports a `StandardOutput` option to choose where you STDOUT to go.  [Docker also plays nice with STDOUT from apps](https://docs.docker.com/engine/reference/commandline/logs/).

Doing a good job at logging over the network is hard, considering you need to prepared for low latency or outages of the destination server where you might want to queue logs.`rsyslog` is expert at this task so let it handle the job.

**Comment by ir-fuel** [comment]
My workaround is that I am currently testing papertrail.

**Comment by ir-fuel** [comment]
Well isn't this just great.
2 production servers:

![screen shot 2016-07-28 at 15 09 43
![screen shot 2016-07-28 at 15 10 00](https://cloud.githubusercontent.com/assets/1573715/17213649/80a62984-54d5-11e6-87ed-450396f13db6.png)
](https://cloud.githubusercontent.com/assets/1573715/17213645/7c540c02-54d5-11e6-99e6-f91a81e7461c.png)

**Comment by ir-fuel** [comment]
Enough is enough. Had it happen again on a few production servers. Switched to Papertrail as a test, using Winston for logging. Works like a charm. So bye bye Logentries, I'll be phasing out all my clients now. (not to mention that the user interface is 100 times more responsive and less buggy in Papertrail). This kind of stuff is too critical to keep messing around and being patient. And it's not exactly for free either.

**Comment by StephenHynes7** [comment]
See https://github.com/rapid7/le_node/pull/122 for those interested

**Comment by StephenHynes7** [comment]
This should be fixed on the latest release 1.6.0 https://www.npmjs.com/package/le_node

**Comment by vinnyoodles** [comment]
@StephenHynes7 we're still getting this issue and we've updated to `v1.6.0`

**Comment by ksullivan** [comment]
@StephenHynes7 @vinnyoodles We're also getting the issue on 1.6.0.

Debug logs:

	26 Aug 2016 11:06:12.853 No connection exists. Creating a new one.
	26 Aug 2016 11:06:12.920 Connected
	26 Aug 2016 11:10:25.520 Cannot write further to this stream.
	26 Aug 2016 11:10:25.525 Returning, buffer is full.
	26 Aug 2016 11:10:25.525 Returning, buffer is full.
	26 Aug 2016 11:10:25.526 Returning, buffer is full.
	26 Aug 2016 11:10:25.526 Returning, buffer is full.
	26 Aug 2016 11:10:25.530 Returning, buffer is full.
	26 Aug 2016 11:10:25.530 Returning, buffer is full.

**Comment by stopal-r7** [comment]
On 1.6.0 we have removed the code pieces that creates these logs @ksullivan 

Maybe something with npm install went wrong and old code is still there?

**Comment by ksullivan** [comment]
@stopal-r7 It looks like if you do `npm install le_node@1.6.0` you get a version of le_node which has `"version": "1.6.0"` in its `package.json` but also doesn't have any of the ringbuffer stuff...

**Comment by StephenHynes7** [comment]
Hmm we did notice some strange stuff when we were publish the package yesterday for a newer version so it could be related. Make sure to be the latest version which is `1.6.2`

**Comment by vinnyoodles** [comment]
@StephenHynes7 Thanks, we'll update today and let you know
