### ISSUE TITLE
Error: Buffer is full - Force flush

### ISSUE THREAD

**Issue by jordanegiuly** [rapid7/le_node#127]
Hello,

My application has not logged to Log entries for a few errors, and I get the `Error: Buffer is full` in my logs.

Can I flush someone the buffer, so that it starts logging again?

Thanks,

**Comment by stopal-r7** [comment]
Hello,

What version are you using @jordanegiuly?

**Comment by jordanegiuly** [comment]
Hi,

Thanks for the reply. We're using le_node version 1.6.0
The application does not have any particular error. Just the buffer gets full and I'd like to flush it without restarting my node process. Is that possible?

Thanks,

**Comment by stopal-r7** [comment]
Hi,

This should be fixed in 1.6.2, can you upgrade and let us know how it goes?

In case of a connection problem, logs get buffered and when the connection is back, buffer gets flushed. You don't have to do anything for this in your code. Enabling `debug` mode in logger help to see what's going on.

Thanks

**Comment by ksullivan** [comment]
@stopal-r7 We've upgraded to 1.6.3 and we're getting the `"Buffer is full, will be shifting records until buffer is drained."` log messages.

Do these debug logs look okay to you?

Did it wait too long to reconnect, causing the buffer to get full?

Is it strange that there's two "disconnected" messages followed by two "connected" messages?

    30 Aug 2016 09:34:32.112 | No connection exists. Creating a new one.
    30 Aug 2016 09:34:32.178 | Connected
    30 Aug 2016 15:04:06.152 | Error occurred during connection: Error: read ECONNRESET
    30 Aug 2016 15:04:06.223 | Socket was disconnected
    30 Aug 2016 15:04:06.611 | No connection exists. Creating a new one.
    30 Aug 2016 15:06:13.878 | Error occurred during connection: Error: connect ETIMEDOUT
    30 Aug 2016 15:06:13.951 | Socket was disconnected
    30 Aug 2016 15:07:32.990 | Buffer is full, will be shifting records until buffer is drained.
    30 Aug 2016 15:08:22.360 | Error occurred during connection: Error: connect ETIMEDOUT
    30 Aug 2016 15:08:23.134 | Trying to reconnect. Times: 1 , previous delay: 1000
    30 Aug 2016 15:08:26.214 | Connected
    30 Aug 2016 15:08:26.283 | No connection exists. Creating a new one.
    30 Aug 2016 15:08:27.016 | Buffer is full, will be shifting records until buffer is drained.
    30 Aug 2016 15:08:41.315 | Connected

**Comment by allenpc** [comment]
Can confirm that we still experience the same problems after upgrading to 1.6.2

**Comment by stopal-r7** [comment]
Hi @ksullivan,
 
Yes logs look OK to me as long as you can confirm that your logs are making it to Logentries? I can see that connection to Logentries endpoint was lost and le_node attempted to reconnect. Logger object was buffering during that time and buffer was filled after some time. As we utilize an internal ring buffer, in case the buffer was filled we start to discard old logs instead of not accepting new logs. There is a time ump from 09:34 to 15:04 which does not make sense to me but anyways.

What is your buffer size? Are you with buffer size defaults(16k)? If so, you may consider increasing buffer limit of the Logger object to 32k or 64k. Looking at your logs and can see that there is a decent load in your application. Buffer was filled in a relatively short time. It will help you to get rid of "Buffer is full, will be shifting records until buffer is drained." log.

Two disconnected followed by two connected looks good, it can be safely ignored.

**Comment by stopal-r7** [comment]
@allenpc, can you upgrade to the latest version(currently 1.6.4)? There has been a problem when publishing 1.6.2 and you can get still get old buffer full, returning logs in that version.

**Comment by ksullivan** [comment]
@stopal-r7 I've set bufferSize to 65536. Here are some new logs. It looks like the connection disconnected at 22:17 and the buffer got full at 23:05, but it's not clear that it tried to connect again during that time...

    2016-08-31T16:38:31.987970+00:00 | No connection exists. Creating a new one.
    2016-08-31T16:38:32.179686+00:00 | Connected
    2016-08-31T19:20:35.631411+00:00 | Error occurred during connection: Error: read ECONNRESET
    2016-08-31T19:20:35.631430+00:00 | Socket was disconnected
    2016-08-31T19:20:36.239652+00:00 | No connection exists. Creating a new one.
    2016-08-31T19:20:36.327549+00:00 | Connected
    2016-08-31T22:11:47.465563+00:00 | Error occurred during connection: Error: read ECONNRESET
    2016-08-31T22:11:47.465769+00:00 | Socket was disconnected
    2016-08-31T22:11:47.932191+00:00 | No connection exists. Creating a new one.
    2016-08-31T22:11:51.024291+00:00 | Connected
    2016-08-31T22:13:24.068159+00:00 | Socket was inactive for 60 seconds. Destroying.
    2016-08-31T22:13:24.068230+00:00 | Closing retry mechanism along with its connection.
    2016-08-31T22:13:24.212233+00:00 | No connection exists. Creating a new one.
    2016-08-31T22:13:24.296704+00:00 | Connected
    2016-08-31T22:13:58.486563+00:00 | Error occurred during connection: Error: read ECONNRESET
    2016-08-31T22:13:58.486867+00:00 | Socket was disconnected
    2016-08-31T22:13:59.002420+00:00 | No connection exists. Creating a new one.
    2016-08-31T22:13:59.085612+00:00 | Connected
    2016-08-31T22:13:59.100828+00:00 | Socket was disconnected
    2016-08-31T22:13:59.507567+00:00 | No connection exists. Creating a new one.
    2016-08-31T22:13:59.576154+00:00 | Connected
    2016-08-31T22:13:59.583672+00:00 | Socket was disconnected
    2016-08-31T22:14:00.133176+00:00 | No connection exists. Creating a new one.
    2016-08-31T22:14:00.200643+00:00 | Socket was disconnected
    2016-08-31T22:14:00.202797+00:00 | Connected
    2016-08-31T22:14:00.203135+00:00 | No connection exists. Creating a new one.
    2016-08-31T22:14:00.270632+00:00 | Connected
    2016-08-31T22:14:01.339546+00:00 | Socket was disconnected
    2016-08-31T22:14:02.832893+00:00 | No connection exists. Creating a new one.
    2016-08-31T22:14:02.907151+00:00 | Connected
    2016-08-31T22:14:03.474726+00:00 | Socket was disconnected
    2016-08-31T22:14:05.097531+00:00 | No connection exists. Creating a new one.
    2016-08-31T22:14:05.170947+00:00 | Socket was disconnected
    2016-08-31T22:14:05.181398+00:00 | Connected
    2016-08-31T22:14:05.182133+00:00 | No connection exists. Creating a new one.
    2016-08-31T22:14:05.431959+00:00 | Socket was disconnected
    2016-08-31T22:14:36.319262+00:00 | Connected
    2016-08-31T22:14:36.319807+00:00 | No connection exists. Creating a new one.
    2016-08-31T22:14:36.399681+00:00 | Connected
    2016-08-31T22:14:39.480440+00:00 | Socket was disconnected
    2016-08-31T22:14:40.694936+00:00 | No connection exists. Creating a new one.
    2016-08-31T22:14:40.767914+00:00 | Connected
    2016-08-31T22:14:40.772195+00:00 | Socket was disconnected
    2016-08-31T22:14:40.925568+00:00 | No connection exists. Creating a new one.
    2016-08-31T22:14:40.992062+00:00 | Connected
    2016-08-31T22:14:40.996496+00:00 | Socket was disconnected
    2016-08-31T22:14:41.007778+00:00 | No connection exists. Creating a new one.
    2016-08-31T22:14:41.199744+00:00 | Socket was disconnected
    2016-08-31T22:14:56.127252+00:00 | Connected
    2016-08-31T22:14:56.127507+00:00 | No connection exists. Creating a new one.
    2016-08-31T22:14:56.209772+00:00 | Connected
    2016-08-31T22:14:56.359100+00:00 | Socket was disconnected
    2016-08-31T22:14:56.426566+00:00 | No connection exists. Creating a new one.
    2016-08-31T22:14:56.499436+00:00 | Connected
    2016-08-31T22:15:03.541462+00:00 | Socket was disconnected
    2016-08-31T22:15:03.897412+00:00 | No connection exists. Creating a new one.
    2016-08-31T22:15:03.971134+00:00 | Socket was disconnected
    2016-08-31T22:15:03.972253+00:00 | Connected
    2016-08-31T22:15:03.972944+00:00 | No connection exists. Creating a new one.
    2016-08-31T22:15:04.055955+00:00 | Connected
    2016-08-31T22:15:04.192740+00:00 | Socket was disconnected
    2016-08-31T22:15:04.539622+00:00 | No connection exists. Creating a new one.
    2016-08-31T22:15:04.612976+00:00 | Connected
    2016-08-31T22:15:04.620343+00:00 | Socket was disconnected
    2016-08-31T22:15:04.971048+00:00 | No connection exists. Creating a new one.
    2016-08-31T22:16:04.760562+00:00 | Socket was inactive for 60 seconds. Destroying.
    2016-08-31T22:16:04.761470+00:00 | Closing retry mechanism along with its connection.
    2016-08-31T22:17:12.221037+00:00 | Error occurred during connection: Error: connect ETIMEDOUT
    2016-08-31T22:17:12.221072+00:00 | Socket was disconnected
    2016-08-31T23:05:19.822153+00:00 | Buffer is full, will be shifting records until buffer is drained.

**Comment by stopal-r7** [comment]
@ksvullivan, this is an interesting pattern. it should have tried to reconnect after 22.17. can you explain or share a code snippet about your use case and Logger options so that I can try to reproduce?

**Comment by ksullivan** [comment]
@stopal-r7 Well this is extremely frustrating. Just had 10 hours of missing logs. On multiple servers too.

Some servers are using le_node@1.6.3 and some are using le_node@1.6.4.

The logger is set up as follows:

    logentriesLogger = new LogentriesLogger
        token: config.logentriesToken
        secure: true
        bufferSize: 65536
        inactivityTimeout: 60 * 1000
        debug: true
        debugLogger: {log: (message) -> console.log "Logentries debug logger. #{message}"}

    logentriesLogger.addListener 'connected', -> console.log 'Logentries logger connected.'
    logentriesLogger.addListener 'disconnected', -> console.log 'Logentries logger disconnected.'
    logentriesLogger.addListener 'error', (err) -> console.log (err?.stack or err)

Similar debug logs this time on one of the servers:

	2016-09-01T16:33:50.793113+00:00 | No connection exists. Creating a new one.
	2016-09-01T16:33:50.972098+00:00 | Connected
	2016-09-01T22:05:19.989260+00:00 | Socket was disconnected
	2016-09-01T22:05:21.075986+00:00 | Connected
	2016-09-01T22:05:22.432110+00:00 | No connection exists. Creating a new one.
	2016-09-01T22:07:29.740673+00:00 | Error occurred during connection: Error: connect ETIMEDOUT
	2016-09-01T22:07:29.741394+00:00 | Socket was disconnected
	2016-09-01T22:07:33.828436+00:00 | Connected
	2016-09-01T22:07:33.828909+00:00 | No connection exists. Creating a new one.
	2016-09-01T22:08:04.979825+00:00 | Connected
	2016-09-01T22:08:34.001999+00:00 | Socket was inactive for 60 seconds. Destroying.
	2016-09-01T22:08:34.002164+00:00 | Closing retry mechanism along with its connection.
	2016-09-01T22:08:35.798864+00:00 | No connection exists. Creating a new one.
	2016-09-01T22:09:31.282174+00:00 | Socket was inactive for 60 seconds. Destroying.
	2016-09-01T22:09:31.282652+00:00 | Closing retry mechanism along with its connection.
	2016-09-01T22:10:43.019285+00:00 | Error occurred during connection: Error: connect ETIMEDOUT
	2016-09-01T22:10:43.019582+00:00 | Socket was disconnected
	2016-09-01T23:02:38.288065+00:00 | Buffer is full, will be shifting records until buffer is drained.

**Comment by ksullivan** [comment]
@stopal-r7 Would it help to add more debug logging in order to determine what's going on here? Do you have any thoughts on what's causing the connection to become disconnected for such a long time?

**Comment by stopal-r7** [comment]
@ksullivan I tried to reproduce this in last couple of days but I couldn't. Looks like you have some network problems. Are you closing connection of Logger in your application by calling closeConnection() method? I will for sure try to add more debug logs around related places soon.

**Comment by ksullivan** [comment]
@stopal-r7 We're not using the `closeConnection` function. Regarding the network, our app is running on Heroku.

**Comment by ksullivan** [comment]
@stopal-r7 I've been having a look at the logs and trying to work out what could be going wrong... As we've discussed before, it looks like there can be more than one socket open at the same time. Could they be conflicting with each other? For example, say we've got a socket that we're happily logging to and then a second socket times out ("Socket was inactive for 60 seconds. Destroying.") which causes closeConnection to be called. Could that cause this issue?

I'm thinking of setting the socket timeout to 0 to see if that helps...

**Comment by ksullivan** [comment]
@stopal-r7 (Our servers log something every 30 seconds, so the "Socket was inactive for 60 seconds. Destroying." should never really be logged)

**Comment by stopal-r7** [comment]
@ksullivan, nice information on this. I believe we should revise our connection creating logic with the help of this. We actually don't let there be two connections opened at the same time. This still does not lead us to the root cause of the problem though.

2016-09-01T22:05:19.989260+00:00 | Socket was disconnected -> on this line socket is getting disconnected without a timeout or error. This is interesting because there should be either an error or timeout before disconnection. I am trying to find out what is causing this behavior.

I will add some more debug log to code soon which hopefully will help us find where the problem is.

**Comment by ksullivan** [comment]
@stopal-r7 FYI I hacked the library to have `connection.setTimeout(0);` and it looks like that may have resolved the issue indirectly.

**Comment by stopal-r7** [comment]
@ksullivan, are your logs making it to Logentries now? Please let us know how it goes.

**Comment by ksullivan** [comment]
@stopal-r7 Yes, it looks like we're no longer getting the "it disconnects, never reconnects, and the buffer gets full" issue after putting no timeout on the socket.

A few thoughts:

1. In the default configuration, I believe this serious bug is still present (And you still can't manually remove the timeout).
2. You could consider updating the code so that it always does `connection.setTimeout(0);` as a quick solution.
3. A better solution, if you would like to keep the "inactivity timeout" functionality, would be to of course fix the underlying issue which appears to only happen when the timeout callback code runs.

**Comment by stopal-r7** [comment]
@ksullivan, thanks for that. Unfortunately I still cannot reproduce this. I am glad to hear that your problems were gone after disabling inactivity timeout. On my local machine, connection gets destroyed after an inactivity timeout and then created again if necessary. I will keep thinking about this, it's always the best to find the underlying issue and fix it rather than fixing the symptoms.

**Comment by allenpc** [comment]
Still having issues with 1.6.5 when logging is sporadic.

No obvious errors in the debug logs:

```
9096:[DEBUG Wed Sep 21 2016 16:17:04 GMT+0000 (UTC)] Logentries le_node:  No connection exists. Creating a new one.
9097:[DEBUG Wed Sep 21 2016 16:17:04 GMT+0000 (UTC)] Logentries le_node:  Connected
9098:[DEBUG Wed Sep 21 2016 16:17:04 GMT+0000 (UTC)] Logentries le_node:  RingBuffer drained.
9099:[DEBUG Wed Sep 21 2016 16:17:19 GMT+0000 (UTC)] Logentries le_node:  Socket was inactive for 15 seconds. Destroying.
9100:[DEBUG Wed Sep 21 2016 16:17:19 GMT+0000 (UTC)] Logentries le_node:  Closing retry mechanism along with its connection.
9101:[DEBUG Wed Sep 21 2016 16:17:20 GMT+0000 (UTC)] Logentries le_node:  Socket was disconnected
9107:[DEBUG Wed Sep 21 2016 16:18:04 GMT+0000 (UTC)] Logentries le_node:  No connection exists. Creating a new one.
9108:[DEBUG Wed Sep 21 2016 16:18:04 GMT+0000 (UTC)] Logentries le_node:  Connected
9109:[DEBUG Wed Sep 21 2016 16:18:04 GMT+0000 (UTC)] Logentries le_node:  RingBuffer drained.
9110:[DEBUG Wed Sep 21 2016 16:18:19 GMT+0000 (UTC)] Logentries le_node:  Socket was inactive for 15 seconds. Destroying.
9111:[DEBUG Wed Sep 21 2016 16:18:19 GMT+0000 (UTC)] Logentries le_node:  Closing retry mechanism along with its connection.
9112:[DEBUG Wed Sep 21 2016 16:18:20 GMT+0000 (UTC)] Logentries le_node:  Socket was disconnected
```

A single periodic log statement is what is triggering the reconnects, but no sign of the entries when tailing/searching in the logentries webapp.

**Comment by stopal-r7** [comment]
@allenpc 'RingBuffer drained.' log shows that it was sent to socket and made it to Logentries. Looks like something else is wrong. Can you check if your token is correct?

**Comment by allenpc** [comment]
@stopal-r7 Unfortunately I know the token is correct because some logs do make it through (only anecdotal at this point, but it seems like the missing logs only occur when logging is very sporadic. More frequent logging seems to rejigger things back to normal)

**Comment by StephenHynes7** [comment]
@allenpc just out of curiosity if you use the disableTimeout do you see any change in behaviour?

**Comment by allenpc** [comment]
@StephenHynes7 Just deployed with the latest npm version and disableTimeout: true, will keep an eye on things and update this thread

**Comment by dev0x10** [comment]
Any update on this issue? I got the same problem

**Comment by stopal-r7** [comment]
@dev0x10, what is your logger configuration like? is there any logs or bug patterns you can share?

**Comment by stopal-r7** [comment]
This issue may be fixed with #140, can you confirm that it is no longer an issue? Feel free to reopen.

**Comment by bradvogel** [comment]
Haven't seen the issue since. Thanks!

**Comment by stopal-r7** [comment]
@bradvogel very nice! Thanks!
